{
    "openapi": "3.0.1",
    "info": {
        "title": "TalanginDong API Documentation",
        "version": "1.0.0",
        "description": "Contact: icarusphantom (discord)\n# Introduction\nWelcome to the TalanginDong API Documentation page!<br>Here you can find information on all the endpoints we have, and how to use them.\n\nThe main API URL is `https://talangindong-api.icarusphantom.dev/`\n## Limits\nSome API endpoints are limited to a maximum amount of requests per 1 minute intervals. If you want increased rate limit, please contact the developer.\n\nEndpoints will respond with headers to assist with managing the rate limit:\n- 'RateLimit-Limit' - The limit of requests per minute.\n- 'RateLimit-Remaining' - The remaining amount of requests allowed for the current minute.\n- 'RateLimit-Reset' - The amount of seconds until the next minute and the reset of the API usages.",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "servers": [
        {
            "url": "https://talangindong-api.icarusphantom.dev/"
        }
    ],
    "tags": [
        {
            "name": "Authentication",
            "description": "Authentication endpoint for TalanginDong mobile application"
        },
        {
            "name": "Friend",
            "description": "Friend endpoint for TalanginDong mobile application"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "jwt"
            }
        },
        "responses": {
            "SuccessNoData": {
                "description": "A successful response",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 200
                                }
                            }
                        }
                    }
                }

            },
            "BadRequest": {
                "description": "Bad request because of missing required data or other thing",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 400
                                },
                                "code": {
                                    "type": "string",
                                    "example": "BAD_REQUEST"
                                },
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "NotAuthorized": {
                "description": "Invalid authorization token",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 401
                                },
                                "code": {
                                    "type": "string",
                                    "example": "UNAUTHORIZED"
                                },
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "NotFound": {
                "description": "The requested data was not found",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 404
                                },
                                "code": {
                                    "type": "string",
                                    "example": "NOT_FOUND"
                                },
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "Conflict": {
                "description": "Conflict when inserting data",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 409
                                },
                                "code": {
                                    "type": "string",
                                    "example": "CONFLICT"
                                },
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "InternalServerError": {
                "description": "An unknown error that happened server side",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "integer",
                                    "example": 500
                                },
                                "code": {
                                    "type": "string",
                                    "example": "INTERNAL_SERVER_ERROR"
                                },
                                "reason": {
                                    "type": "string"
                                },
                                "stack": {
                                    "type": "string",
                                    "nullable": true
                                }
                            }
                        }
                    }
                }
            }
        },
        "schemas": {
            "Booster": {
                "properties": {
                    "_id": {
                        "type": "string",
                        "format": "objectid"
                    },
                    "purchaserUuid": {
                        "type": "string",
                        "format": "uuid",
                        "example": "ad8fefaa8351454bb739a4eaa872173f"
                    },
                    "amount": {
                        "type": "number"
                    },
                    "originalLength": {
                        "type": "integer"
                    },
                    "length": {
                        "type": "integer"
                    },
                    "gameType": {
                        "type": "integer"
                    },
                    "dateActivated": {
                        "type": "integer",
                        "format": "int64"
                    }
                }
            },
            "ActiveBooster": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/Booster"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "stacked": {
                                "type": "array",
                                "nullable": true,
                                "items": {
                                    "type": "string",
                                    "description": "UUID of the player in a dashed format",
                                    "format": "uuid",
                                    "example": "ad8fefaa-8351-454b-b739-a4eaa872173f"
                                }
                            }
                        }
                    }
                ]
            },
            "QueuedBooster": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/Booster"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "stacked": {
                                "type": "boolean",
                                "nullable": true
                            }
                        }
                    }
                ]
            },
            "SkyBlockAuction": {
                "properties": {
                    "_id": {
                        "type": "string",
                        "format": "objectid"
                    },
                    "uuid": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "auctioneer": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "profile_id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "coop": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "format": "uuid"
                        }
                    },
                    "start": {
                        "type": "number",
                        "format": "int64"
                    },
                    "end": {
                        "type": "number",
                        "format": "int64"
                    },
                    "item_name": {
                        "type": "string"
                    },
                    "item_lore": {
                        "type": "string"
                    },
                    "extra": {
                        "type": "string"
                    },
                    "category": {
                        "type": "string"
                    },
                    "tier": {
                        "type": "string"
                    },
                    "starting_bid": {
                        "type": "number"
                    },
                    "item_bytes": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "number"
                            },
                            "data": {
                                "type": "string"
                            }
                        }
                    },
                    "claimed": {
                        "type": "boolean"
                    },
                    "claimed_bidders": {
                        "type": "array"
                    },
                    "highest_bid_amount": {
                        "type": "number"
                    },
                    "bids": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "auction_id": {
                                    "type": "string",
                                    "format": "uuid"
                                },
                                "bidder": {
                                    "type": "string",
                                    "format": "uuid"
                                },
                                "profile_id": {
                                    "type": "string",
                                    "format": "uuid"
                                },
                                "amount": {
                                    "type": "number"
                                },
                                "timestamp": {
                                    "type": "number",
                                    "format": "int64"
                                }
                            }
                        }
                    }
                },
                "example": {
                    "_id": "5dcdaf2244f4f4f350c02bf3",
                    "uuid": "409a1e0f261a49849493278d6cd9305a",
                    "auctioneer": "347ef6c1daac45ed9d1fa02818cf0fb6",
                    "profile_id": "347ef6c1daac45ed9d1fa02818cf0fb6",
                    "coop": [
                        "347ef6c1daac45ed9d1fa02818cf0fb6"
                    ],
                    "start": 1573760802637,
                    "end": 1573761102637,
                    "item_name": "Azure Bluet",
                    "item_lore": "§f§lCOMMON",
                    "extra": "Azure Bluet Red Rose",
                    "category": "blocks",
                    "tier": "COMMON",
                    "starting_bid": 1,
                    "item_bytes": {
                        "type": 0,
                        "data": "H4sIAAAAAAAAAB2NQQqCQBhGv1ErHaKu0KoLtGtnarRIhTpA/OGfDIwZ4wxUF/IeHiyyto/3eBKIIJQEIDx4qsJaYJK07m6FhG+p9hEdVMV7TXU3Wh+JWaW6h6ZXhODYGg5/LeZDfxt6nZR5XhYhgoIaxmKE8dsZXu20YwuJZfa0hmJrjbo6y134f8pTll5O5TnbbgAP05Qaqhk+8AVIrd2eoAAAAA=="
                    },
                    "claimed": true,
                    "claimed_bidders": [],
                    "highest_bid_amount": 7607533,
                    "bids": [
                        {
                            "auction_id": "409a1e0f261a49849493278d6cd9305a",
                            "bidder": "99748e629dee463892f68abf3a780094",
                            "profile_id": "99748e629dee463892f68abf3a780094",
                            "amount": 7607533,
                            "timestamp": 1573760824844
                        }
                    ]
                }
            },
            "SkyBlockProfile": {
                "properties": {
                    "profile_id": {
                        "type": "string",
                        "format": "uuid"
                    },
                    "members": {
                        "description": "A map of member UUIDs to member profiles objects",
                        "type": "object",
                        "properties": {
                            "player_id": {
                                "type": "string",
                                "format": "uuid"
                            },
                            "deletion_notice": {
                                "description": "If this field exists, the member profile is marked as deleted",
                                "nullable": true,
                                "type": "object",
                                "properties": {
                                    "timestamp": {
                                        "type": "integer",
                                        "format": "int64"
                                    }
                                }
                            }
                        }
                    },
                    "cute_name": {
                        "description": "The cute name of the profile, only provided on the profiles endpoint",
                        "nullable": true,
                        "type": "string"
                    },
                    "selected": {
                        "description": "Whether or not this is the currently selected profile, only provided on the profiles endpoint",
                        "nullable": true,
                        "type": "boolean"
                    },
                    "community_upgrades": {
                        "nullable": true,
                        "type": "object"
                    },
                    "banking": {
                        "description": "Information about the bank account for this profile, only present if the API banking setting is enabled",
                        "nullable": true,
                        "type": "object",
                        "properties": {
                            "balance": {
                                "type": "number",
                                "format": "double"
                            },
                            "transactions": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "timestamp": {
                                            "type": "integer",
                                            "format": "int64"
                                        },
                                        "action": {
                                            "type": "string",
                                            "enum": [
                                                "DEPOSIT",
                                                "WITHDRAW"
                                            ]
                                        },
                                        "initiator_name": {
                                            "type": "string"
                                        },
                                        "amount": {
                                            "type": "number",
                                            "format": "double"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "game_mode": {
                        "description": "The SkyBlock game mode of the profile, not present if normal mode",
                        "nullable": true,
                        "type": "string",
                        "enum": [
                            "ironman",
                            "island",
                            "bingo"
                        ]
                    }
                }
            },
            "SkyBlockItem": {
                "properties": {
                    "id": {
                        "description": "The unique identifier for this item",
                        "type": "string"
                    },
                    "material": {
                        "description": "The Bukkit material enum value for the item",
                        "type": "string"
                    },
                    "name": {
                        "description": "The name of the item",
                        "type": "string"
                    },
                    "tier": {
                        "description": "The rarity tier of the item",
                        "type": "string",
                        "enum": [
                            "COMMON",
                            "UNCOMMON",
                            "RARE",
                            "EPIC",
                            "LEGENDARY",
                            "MYTHIC",
                            "SUPREME",
                            "SPECIAL",
                            "VERY_SPECIAL"
                        ]
                    },
                    "color": {
                        "description": "The color metadata to be applied to an item, usually leather armor pieces",
                        "pattern": "^(?:(?:^|,\\s*)([01]?\\d\\d?|2[0-4]\\d|25[0-5])){3}$",
                        "type": "string"
                    },
                    "skin": {
                        "description": "The skin value for a skull based item",
                        "type": "string"
                    }
                },
                "example": {
                    "material": "LEATHER_CHESTPLATE",
                    "color": "255,215,0",
                    "name": "Farm Armor Chestplate",
                    "category": "CHESTPLATE",
                    "tier": "RARE",
                    "stats": {
                        "DEFENSE": 75,
                        "HEALTH": 20
                    },
                    "npc_sell_price": 5200,
                    "id": "FARM_ARMOR_CHESTPLATE"
                }
            },
            "SkyBlockMuseum": {
                "properties": {
                    "value": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "appraisal": {
                        "type": "boolean"
                    },
                    "items": {
                        "type": "object"
                    },
                    "special": {
                        "type": "array",
                        "properties": {
                            "donated_time": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            },
            "Game": {
                "description": "Information about a specific game. When a field is not present you should fallback to the provided default if there is one, required fields will always exist.",
                "required": [
                    "id",
                    "name",
                    "databaseName"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "description": "The backend ID of the game.",
                        "example": 1
                    },
                    "name": {
                        "type": "string",
                        "description": "The display name of the game.",
                        "example": "Bed Wars"
                    },
                    "databaseName": {
                        "type": "string",
                        "description": "The key used for database storage, such as for stats.",
                        "example": "Bedwars"
                    },
                    "modeNames": {
                        "type": "object",
                        "description": "A map of mode key to display name",
                        "example": {
                            "solo_normal": "Solo",
                            "team_normal": "Doubles"
                        }
                    },
                    "retired": {
                        "type": "boolean",
                        "description": "True if the game is retired and no longer playable.",
                        "default": false
                    },
                    "legacy": {
                        "type": "boolean",
                        "description": "True if the game is legacy and part of the Classic Lobby.",
                        "default": false
                    }
                },
                "example": {
                    "id": 58,
                    "name": "Bed Wars",
                    "databaseName": "Bedwars",
                    "modeNames": {
                        "BEDWARS_TWO_FOUR": "4v4",
                        "BEDWARS_EIGHT_ONE": "Solo"
                    }
                }
            },
            "SkyBlockFireSale": {
                "properties": {
                    "item_id": {
                        "description": "The SkyBlock item ID for this sale",
                        "type": "string"
                    },
                    "start": {
                        "description": "The start time in unix milliseconds for the sale",
                        "type": "number"
                    },
                    "end": {
                        "description": "The end time in unix milliseconds for the sale",
                        "type": "number"
                    },
                    "amount": {
                        "description": "The amount of items available for this sale",
                        "type": "integer"
                    },
                    "price": {
                        "description": "The price in Gems for this sale",
                        "type": "integer"
                    }
                }
            }
        }
    },
    "paths": {
        "/v1/auth/register": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Register",
                "description": "Endpoint for registering new account.",
                "operationId": "signup",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "409": {
                        "$ref": "#/components/responses/Conflict"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "description": "Endpoint for login account.",
                "operationId": "login",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "A successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                },
                                                "refreshToken": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "404": {
                        "$ref": "#/components/responses/NotFound"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/auth/refresh-token": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh Token",
                "description": "Endpoint for refreshing token.",
                "operationId": "refreshToken",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "refreshToken": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "A successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/list": {
            "get": {
                "tags": [
                    "Friend"
                ],
                "summary": "Friend List",
                "description": "Endpoint for getting friend list.",
                "operationId": "list",
                "security": [{
                    "bearerAuth": []
                }],
                "responses": {
                    "200": {
                        "description": "A successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "username": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/search": {
            "get": {
                "tags": [
                    "Friend"
                ],
                "summary": "Search Friend",
                "description": "Endpoint for searching friend.",
                "operationId": "search",
                "security": [{
                    "bearerAuth": []
                }],
                "parameters": [
                    {
                        "in": "query",
                        "name": "search",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "username": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/pending": {
            "get": {
                "tags": [
                    "Friend"
                ],
                "summary": "Pending Friend Request",
                "description": "Endpoint for getting list of pending friend request.",
                "operationId": "pending",
                "security": [{
                    "bearerAuth": []
                }],
                "responses": {
                    "200": {
                        "description": "A successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "username": {
                                                        "type": "string"
                                                    },
                                                    "status": {
                                                        "type": "integer",
                                                        "enum": [
                                                            0,
                                                            1
                                                        ]
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/request": {
            "post": {
                "tags": [
                    "Friend"
                ],
                "summary": "Request friend",
                "description": "Endpoint for requesting friend.",
                "operationId": "request",
                "security": [{
                    "bearerAuth": []
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "recipientId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "409": {
                        "$ref": "#/components/responses/Conflict"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/accept": {
            "put": {
                "tags": [
                    "Friend"
                ],
                "summary": "Accept Friend",
                "description": "Endpoint for accepting friend.",
                "operationId": "accept",
                "security": [{
                    "bearerAuth": []
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "requesterId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "404": {
                        "$ref": "#/components/responses/NotFound"
                    },
                    "409": {
                        "$ref": "#/components/responses/Conflict"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/cancel": {
            "delete": {
                "tags": [
                    "Friend"
                ],
                "summary": "Cancel Friend Request.",
                "description": "Endpoint for cancelling friend request.",
                "operationId": "cancel",
                "security": [{
                    "bearerAuth": []
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "recipientId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "404": {
                        "$ref": "#/components/responses/NotFound"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/reject": {
            "delete": {
                "tags": [
                    "Friend"
                ],
                "summary": "Reject Friend Request.",
                "description": "Endpoint for rejecting friend request.",
                "operationId": "reject",
                "security": [{
                    "bearerAuth": []
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "requesterId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "404": {
                        "$ref": "#/components/responses/NotFound"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        },
        "/v1/friend/remove": {
            "delete": {
                "tags": [
                    "Friend"
                ],
                "summary": "Remove Friend",
                "description": "Endpoint for removing friend.",
                "operationId": "remove",
                "security": [{
                    "bearerAuth": []
                }],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "friendId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/SuccessNoData"
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/NotAuthorized"
                    },
                    "404": {
                        "$ref": "#/components/responses/NotFound"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            }
        }
    }
}